(() => {
const p=new URLSearchParams(location.search),source=p.get('source');if(!['curatoros','content-opportunity'].includes(source))return;let pageUrl;try{pageUrl=new URL(p.get('url')||'')}catch{return}if(!['oceanliners.net','www.oceanliners.net'].includes(pageUrl.hostname.toLowerCase()))return;
const clean=v=>String(v||'').trim().slice(0,1500),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),mode=p.get('mode')==='create'?'create':'edit',title=clean(p.get('finding_title'))||'Content Opportunity',category=clean(p.get('finding_category')),recommendation=clean(p.get('recommendation')),rationale=clean(p.get('rationale')),notes=clean(p.get('notes')),id=clean(p.get('opportunity_id')),cluster=clean(p.get('cluster')),template=clean(p.get('template_hint'));
const loader=document.querySelector('.loader-panel'),input=document.querySelector('#page-url'),button=document.querySelector('#load-url'),editor=document.querySelector('#code-editor');if(!loader||!input||!button)return;
const panel=document.createElement('section');panel.className='handoff-panel';panel.innerHTML=`<div class="handoff-panel__heading"><div><span class="eyebrow">${mode==='create'?'New-page brief from Content Opportunity Finder':source==='content-opportunity'?'Editorial handoff from Content Opportunity Finder':'Repair handoff from CuratorOS'}</span><h2>${esc(title)}</h2></div>${category?`<span class="handoff-panel__category">${esc(category)}</span>`:''}</div><div class="handoff-panel__details">${recommendation?`<p><strong>Recommended work</strong><span>${esc(recommendation)}</span></p>`:''}${rationale?`<p><strong>Why this work</strong><span>${esc(rationale)}</span></p>`:''}${cluster?`<p><strong>Content cluster</strong><span>${esc(cluster)}</span></p>`:''}${template?`<p><strong>Template hint</strong><span>${esc(template)}</span></p>`:''}${notes?`<p><strong>Curator notes</strong><span>${esc(notes)}</span></p>`:''}${id?`<p><strong>Opportunity record</strong><span>${esc(id)}</span></p>`:''}</div><div class="handoff-panel__actions">${mode==='edit'?`<a href="${esc(pageUrl.href)}" target="_blank" rel="noopener">Inspect live page</a>`:''}<a href="${source==='content-opportunity'?'https://content.oceanliners.net/':'https://curator.oceanliners.net/'}">Back to ${source==='content-opportunity'?'Content Opportunity Finder':'CuratorOS'}</a></div>`;loader.insertAdjacentElement('afterend',panel);input.value=pageUrl.href;
const pathInput=document.querySelector('#repo-path'),branchInput=document.querySelector('#branch-name'),commitInput=document.querySelector('#commit-message');let path=clean(p.get('suggested_path'))||pageUrl.pathname;path=path.replace(/^\/+|\/+$/g,'')||'index';if(!/\.[a-z0-9]+$/i.test(path))path+='.html';if(pathInput&&!pathInput.value.trim())pathInput.value=path;const slug=pageUrl.pathname.split('/').filter(Boolean).pop()||'page';if(branchInput&&(!branchInput.value.trim()||branchInput.value==='page-studio-edit'))branchInput.value=`page-studio-${mode==='create'?'create':'opportunity'}-${slug}-${Date.now().toString(36)}`;if(commitInput&&(!commitInput.value.trim()||commitInput.value==='Edit page in Page Studio'))commitInput.value=`${mode==='create'?'Create':'Edit'} ${title} in Page Studio`;
if(mode==='create'){
 const description=(recommendation||`A new Ocean Liner Curator page about ${title}`).replace(/"/g,'&quot;');const brief=[recommendation,rationale,cluster?`Cluster: ${cluster}`:'',template?`Template hint: ${template}`:'',notes].filter(Boolean).join(' | ').replace(/--/g,'—');const html=`<!doctype html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width,initial-scale=1">\n  <title>${esc(title)} · Ocean Liner Curator</title>\n  <meta name="description" content="${description}">\n  <link rel="canonical" href="${esc(pageUrl.href)}">\n</head>\n<body>\n  <!-- CuratorOS opportunity: ${esc(id)} -->\n  <!-- Editorial brief: ${esc(brief)} -->\n  <main>\n    <article>\n      <p class="eyebrow">Ocean Liner Curator</p>\n      <h1>${esc(title)}</h1>\n      <p><strong>Editorial brief:</strong> ${esc(recommendation||'Develop this accepted CuratorOS content opportunity.')}</p>\n      <section>\n        <h2>Draft workspace</h2>\n        <p>Begin the researched page here. Replace this scaffold with the appropriate Ocean Liner Curator house template before publication.</p>\n      </section>\n    </article>\n  </main>\n</body>\n</html>`;
 if(editor){editor.value=html;editor.dispatchEvent(new Event('input',{bubbles:true}))}const status=document.querySelector('#status');if(status)status.textContent='New-page workspace created from the accepted Content Opportunity brief.';panel.scrollIntoView({block:'start'});return;
}
queueMicrotask(()=>{button.click();panel.scrollIntoView({block:'start'})});
})();