(() => {
  const params=new URLSearchParams(location.search),source=params.get('source');
  if(!['curatoros','content-opportunity'].includes(source))return;
  const raw=params.get('url')||'';let pageUrl;try{pageUrl=new URL(raw)}catch{return}if(!['oceanliners.net','www.oceanliners.net'].includes(pageUrl.hostname.toLowerCase()))return;
  const clean=v=>String(v||'').trim().slice(0,1500),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const title=clean(params.get('finding_title'))||(source==='content-opportunity'?'Content Opportunity':'CuratorOS finding'),category=clean(params.get('finding_category')),recommendation=clean(params.get('recommendation')),rationale=clean(params.get('rationale')),notes=clean(params.get('notes')),opportunityId=clean(params.get('opportunity_id'));
  const loader=document.querySelector('.loader-panel'),input=document.querySelector('#page-url'),button=document.querySelector('#load-url');if(!loader||!input||!button)return;
  const panel=document.createElement('section');panel.className='handoff-panel';panel.innerHTML=`<div class="handoff-panel__heading"><div><span class="eyebrow">${source==='content-opportunity'?'Editorial handoff from Content Opportunity Finder':'Repair handoff from CuratorOS'}</span><h2>${esc(title)}</h2></div>${category?`<span class="handoff-panel__category">${esc(category)}</span>`:''}</div><div class="handoff-panel__details">${recommendation?`<p><strong>Recommended work</strong><span>${esc(recommendation)}</span></p>`:''}${rationale?`<p><strong>Why this work</strong><span>${esc(rationale)}</span></p>`:''}${notes?`<p><strong>Curator notes</strong><span>${esc(notes)}</span></p>`:''}${opportunityId?`<p><strong>Opportunity record</strong><span>${esc(opportunityId)}</span></p>`:''}</div><div class="handoff-panel__actions"><a href="${esc(pageUrl.href)}" target="_blank" rel="noopener">Inspect live page</a><a href="${source==='content-opportunity'?'https://content.oceanliners.net/':'https://curator.oceanliners.net/'}">Back to ${source==='content-opportunity'?'Content Opportunity Finder':'CuratorOS'}</a></div>`;
  loader.insertAdjacentElement('afterend',panel);input.value=pageUrl.href;
  const pathInput=document.querySelector('#repo-path'),branchInput=document.querySelector('#branch-name'),commitInput=document.querySelector('#commit-message');let path=pageUrl.pathname.replace(/^\/+|\/+$/g,'')||'index';if(!/\.[a-z0-9]+$/i.test(path))path+='.html';if(pathInput&&!pathInput.value.trim())pathInput.value=path;const slug=pageUrl.pathname.split('/').filter(Boolean).pop()||'page';if(branchInput&&(!branchInput.value.trim()||branchInput.value==='page-studio-edit'))branchInput.value=`page-studio-${source==='content-opportunity'?'opportunity':'repair'}-${slug}-${Date.now().toString(36)}`;if(commitInput&&(!commitInput.value.trim()||commitInput.value==='Edit page in Page Studio'))commitInput.value=source==='content-opportunity'?`${String(params.get('opportunity_type')||'Edit').toUpperCase()} ${title} in Page Studio`:`Repair ${title} in Page Studio`;
  queueMicrotask(()=>{button.click();panel.scrollIntoView({block:'start'})});
})();