name = "page-studio-loader"
main = "src/index.js"
compatibility_date = "2026-07-28"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://page-studio.pages.dev,https://page-studio.oceanliners.net"
ALLOWED_REPOSITORY = "jaredmberger/ocean-liner-curator"
GITHUB_BASE_BRANCH = "main"
